# =================================================================== #
#                 LionUtils Configuration File                        #
# =================================================================== #
# For help: https://github.com/LionCraft08/LionUtils/                 #
# =================================================================== #

# IMPORTANT: Do not change this version number. It is used by the plugin
# to automatically update the configuration with new settings.
config-version: 1.4



inventory-view:
  allow-changes: true
  update: true
advanced-spectator:
  allow-world-interactions: true

# Settings for the custom Tab List Header (and Footer)
# If connected to a LionVelocity Proxy, this Server will stop sending custom Tab List designs,
# so the Velocity Configuration isn't overwritten.
tablist:
  time-zone: Europe/Berlin
  time-format: dd.MM.yyyy    HH:mm z
  server-name: Survival 01
  #Utilizes the Methods of LionAPI to generate the Gradient for the separator line
  #as it looks way better by default than MiniMessage.
  #You should disable it if you want to change the colors.
  use-lionapi-gradiant: true


structure:
  #Allows players in creative mode to destroy and place blocks in a placed structure
  allow-edits-in-creative: true


  #Mainly used by the reset Command, may get changed during runtime, however, value can be manually changed.
delete-worlds-on-startup: false

#Whether to allow using the /reset command. set this to false if you have a world you don't want to be deleted.
allow-reset: true

modts:
  withonlineplayers:
    - '%playername% mag Züge!'
    - '%playername% wurde gerade von Delfinen getötet!'
    - '%playername% mag keine Tomaten!'
    - 'Vorsicht vor %playername%!'
    - 'Leg dich niemals mit %playername% an!'
    - '%playername% spielt League of Legends!'
    - '%playername% mag Phantome'
    - '%playername% isst gerade Brokkoli!'
    - '%playername% kann nicht bauen...'
  noonlineplayers:
    - Schlechte Laune wird hier nicht toleriert!
    - 1+2+3 = 1*2*3
    - English or Spanish?
    - Rollt eine Kugel um die Ecke und fällt um!
    - Minecraft is cool!
    - Sport ist gesund!
    - MEINE CHICKEN NUGGETS VERBRENNEN!!!
    - Ist das ihr Kontostand oder ihre IBAN?
    - Work hard dream big!
    - Manchmal ist ein Block mehr als nur ein Block
    - Liebe auf den ersten Block
    - Ich kam, sah, und vergaß was ich vorhatte.
    - Je weniger man zuhört, desto professioneller sollte man nicken!
    - Sometimes, you need to mine deep to find your diamonds
    - The journey is just as important as the destination
settings:
  block-to-expensive: false
  status:
    #Time in Seconds until AFK gets displayed as Status.
    afktimer: 120
    enabled-by-default: true

#Used to find Worlds before Server startup
detected-worlds:

files-to-reset:
